# ~/.config/zsh/zshenv
# Defines global environment variables for all Zsh sessions

# Base directories
export XDG_CONFIG_HOME="$HOME/.config"  # Symlinked from ~/.config where possible
export CF="$XDG_CONFIG_HOME"
export DOTZ="$HOME/.config/zsh"           # Real files in ~/.config/zsh
export RX="$HOME/.config/rx"              # Real files in ~/.config/rx
export NV="$HOME/il-diab"
export NTS="$HOME/notes"
export DX="$HOME/Documents"
export DN="$HOME/Downloads"
export SCS="$DX/webpage"
export SUSO="$HOME/sucias-social"
export CAPTURE_FOLDER="$HOME/Pictures"

# Tool-specific settings
export PATH="$HOME/myCommands:$HOME/myCommands/bin:/opt/homebrew/opt/ruby/bin:$HOME/.cargo/bin:$HOME/.local/bin:$RX:$PATH"  # Add $RX to PATH
export FZF_DEFAULT_OPTS='--height=20% --cycle --info=hidden --tabstop=4 --black'
export CLICOLOR=1
export EDITOR='nvim'

# Set MAKEFLAGS based on system type
if [[ "$(uname)" == "Darwin" ]]; then
  if [[ "$(sysctl -n hw.cputype)" == "16777228" ]]; then
    export MAKEFLAGS="-j$(sysctl -n hw.ncpu)"  # Apple Silicon
  else
    export MAKEFLAGS="-j$(sysctl -n hw.ncpu)"  # Intel
  fi
elif [[ "$(uname)" == "Linux" ]]; then
  export MAKEFLAGS="-j$(nproc)"
fi

export FUNCNEST=25000

# Homebrew path
export PATH="/opt/homebrew/bin:$PATH"

# Golang settings
export GOROOT="/opt/homebrew/opt/go/libexec"
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Source zprofile
source "$DOTZ/zprofile"
source <(carapace _carapace zsh)
