# Enable Powerlevel10k instant prompt. Should stay close to the top of ${HOME}/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Ensure XDG_BIN_HOME is in PATH
if ! [[ $PATH == "$XDG_BIN_HOME"* ]]; then
  export PATH="$XDG_BIN_HOME:$PATH"
fi

# Set various environment variables
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

export XDG_CONFIG_HOME="$HOME/.config"
export CF="$HOME/.config"
export DOTZ="$CF/zsh"
export RX="$CF/rx"
export NV="$HOME/.lua-is-the-devil"
export NOT="$HOME/notes"
export DX="$HOME/Documents"
export DN="$HOME/Downloads"
export SCS="$DX/webpage"
export SUSO="$HOME/sucias-social"
export FUNCNEST=25000

# Set directory to store zinit and plugs
ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"

# Download Zinit if it doesn't exist
if [[ ! -d "$ZINIT_HOME" ]]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit "$ZINIT_HOME"
fi

# Source / load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Load plugins using zinit
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit light Aloxaf/fzf-tab

# Load completions
autoload -U compinit && compinit
zinit cdreplay -q

# Load Powerlevel10k configuration if it exists
[[ ! -f ${HOME}/.config/p10k.zsh ]] || source ${HOME}/.config/p10k.zsh

zle_keymap-select(){
case $KEYMAP$ZLE_STATE in
  # block
  vicmd*) print -n "\e[2 q";;
esac
}
# Keybindings
bindkey -v
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward
bindkey '^[w' kill-region

HYPHEN_INSENSITIVE="true"
# History settings
HISTSIZE=5000
HISTFILE=${HOME}/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
HISTORY_IGNORE="mv*|ls*|lt*|ld*|c*|\$*|or|cp*|..*|mtt|source*|bu|brm*|la*|"

# History options
setopt auto_cd
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
# Debugging: Ensure files exist and are readable
for script in $DOTZ/scripts/*.zsh; do
  source "$script" > /dev/null
done
  source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source $(brew --prefix)/share/zsh-autopair/autopair.zsh
  source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  source $(brew --prefix)/share/zsh-completions

# Initialize fzf and zoxide
  source <(fzf --zsh)
  eval "$(zoxide init zsh)"

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
